export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const EDIT_USER = 'EDIT_USER';
export const FETCH_OVERVIEW_REPORTS = 'FETCH_OVERVIEW_REPORTS';
export const FETCH_REQUIRED_USERS = 'FETCH_REQUIRED_USERS';
export const ADD_EDIT_USER = 'ADD_EDIT_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';

